breed_data = {
  "breeds": {
    "Alambadi": {
      "origin": "Tamil Nadu, India",
      "purpose": "Draught / Low-milk",
      "milk_yield_liters_per_day": "1–3",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Grey to dark coat, medium horns curving outward",
      "climate_adaptation": "Tolerant to heat, hardy in dry tracts",
      "average_weight_male_kg": 420,
      "average_weight_female_kg": 300,
      "temperament": "Alert, active",
      "lifespan_years": 12
    },
    "Amritmahal": {
      "origin": "Karnataka, India",
      "purpose": "Draught",
      "milk_yield_liters_per_day": "1–3",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Grey/white, long head, powerful withers",
      "climate_adaptation": "Very heat-hardy, long-distance draught",
      "average_weight_male_kg": 500,
      "average_weight_female_kg": 340,
      "temperament": "Spirited",
      "lifespan_years": 12
    },
    "Ayrshire": {
      "origin": "Scotland",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "20–30",
      "milk_fat_percentage": "4.0–4.3",
      "physical_traits": "Red and white markings, medium frame",
      "climate_adaptation": "Cool–temperate; good grazer",
      "average_weight_male_kg": 650,
      "average_weight_female_kg": 500,
      "temperament": "Active, manageable",
      "lifespan_years": 10
    },
    "Banni": {
      "origin": "Kutch, Gujarat, India (buffalo)",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "6–12",
      "milk_fat_percentage": "6.5–8.0",
      "physical_traits": "Black, sickle-shaped horns, compact body",
      "climate_adaptation": "Excellent heat and drought tolerance",
      "average_weight_male_kg": 550,
      "average_weight_female_kg": 450,
      "temperament": "Docile",
      "lifespan_years": 15
    },
    "Bargur": {
      "origin": "Tamil Nadu, India",
      "purpose": "Draught",
      "milk_yield_liters_per_day": "2–5",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Reddish-brown with white patches, tight skin",
      "climate_adaptation": "Hill tracts; heat and parasite tolerant",
      "average_weight_male_kg": 430,
      "average_weight_female_kg": 300,
      "temperament": "Alert, sometimes skittish",
      "lifespan_years": 12
    },
    "Bhadawari": {
      "origin": "UP–MP border, India (buffalo)",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "3–8",
      "milk_fat_percentage": "7.5–12.0",
      "physical_traits": "Coppery sheen on black coat, thin horns",
      "climate_adaptation": "Hot, semi-arid tolerance",
      "average_weight_male_kg": 500,
      "average_weight_female_kg": 400,
      "temperament": "Calm",
      "lifespan_years": 15
    },
    "Brown_Swiss": {
      "origin": "Switzerland",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "18–30",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Solid brown coat, strong feet & legs",
      "climate_adaptation": "Wide; good heat tolerance for a European breed",
      "average_weight_male_kg": 900,
      "average_weight_female_kg": 600,
      "temperament": "Docile",
      "lifespan_years": 10
    },
    "Dangi": {
      "origin": "Maharashtra, India",
      "purpose": "Draught",
      "milk_yield_liters_per_day": "2–6",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Speckled (black/white), strong hooves",
      "climate_adaptation": "Monsoon zones; excellent in rain & mud",
      "average_weight_male_kg": 420,
      "average_weight_female_kg": 300,
      "temperament": "Hardy, steady",
      "lifespan_years": 12
    },
    "Deoni": {
      "origin": "Maharashtra–Karnataka, India",
      "purpose": "Dual (milk/draught)",
      "milk_yield_liters_per_day": "4–10",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "White with black face/patches, deep body",
      "climate_adaptation": "Heat tolerant, hardy",
      "average_weight_male_kg": 500,
      "average_weight_female_kg": 380,
      "temperament": "Docile",
      "lifespan_years": 12
    },
    "Gir": {
      "origin": "Gujarat, India",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "12–25",
      "milk_fat_percentage": "4.5–5.0",
      "physical_traits": "Red/white patches, convex forehead, pendulous ears",
      "climate_adaptation": "Excellent heat/disease tolerance",
      "average_weight_male_kg": 550,
      "average_weight_female_kg": 400,
      "temperament": "Docile",
      "lifespan_years": 12
    },
    "Guernsey": {
      "origin": "Channel Islands (UK)",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "16–28",
      "milk_fat_percentage": "4.5–5.0",
      "physical_traits": "Fawn/red with white, medium frame",
      "climate_adaptation": "Temperate; good grazer",
      "average_weight_male_kg": 700,
      "average_weight_female_kg": 475,
      "temperament": "Quiet",
      "lifespan_years": 10
    },
    "Hallikar": {
      "origin": "Karnataka, India",
      "purpose": "Draught",
      "milk_yield_liters_per_day": "2–5",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Grey/white, long curved horns",
      "climate_adaptation": "Tropical heat; endurance",
      "average_weight_male_kg": 430,
      "average_weight_female_kg": 320,
      "temperament": "Active",
      "lifespan_years": 12
    },
    "Hariana": {
      "origin": "Haryana, India",
      "purpose": "Dual (draught/milk)",
      "milk_yield_liters_per_day": "3–8",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "White/grey coat, lyre-shaped horns",
      "climate_adaptation": "Heat/drought tolerant",
      "average_weight_male_kg": 430,
      "average_weight_female_kg": 310,
      "temperament": "Calm, willing worker",
      "lifespan_years": 12
    },
    "Holstein_Friesian": {
      "origin": "Netherlands/Germany",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "25–40",
      "milk_fat_percentage": "3.5–4.0",
      "physical_traits": "Black & white piebald, very large frame",
      "climate_adaptation": "Best in temperate; needs shade in heat",
      "average_weight_male_kg": 900,
      "average_weight_female_kg": 650,
      "temperament": "Calm but active",
      "lifespan_years": 9
    },
    "Jaffrabadi": {
      "origin": "Saurashtra, Gujarat, India (buffalo)",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "6–14",
      "milk_fat_percentage": "6.0–7.5",
      "physical_traits": "Massive body, heavy horns drooping back",
      "climate_adaptation": "Heat tolerant",
      "average_weight_male_kg": 800,
      "average_weight_female_kg": 600,
      "temperament": "Docile, powerful",
      "lifespan_years": 15
    },
    "Jersey": {
      "origin": "Channel Islands (UK)",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "15–25",
      "milk_fat_percentage": "4.8–5.6",
      "physical_traits": "Light brown/fawn, dished face, small frame",
      "climate_adaptation": "Adaptable; good in heat with shade",
      "average_weight_male_kg": 700,
      "average_weight_female_kg": 450,
      "temperament": "Docile",
      "lifespan_years": 10
    },
    "Kangayam": {
      "origin": "Tamil Nadu, India",
      "purpose": "Draught",
      "milk_yield_liters_per_day": "2–6",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Grey coat, strong compact body, short horns",
      "climate_adaptation": "Dry tracts; heat hardy",
      "average_weight_male_kg": 500,
      "average_weight_female_kg": 350,
      "temperament": "Steady",
      "lifespan_years": 12
    },
    "Kankrej": {
      "origin": "Gujarat–Rajasthan, India",
      "purpose": "Dual (milk/draught)",
      "milk_yield_liters_per_day": "8–12",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Silver-grey to iron-grey, lyre horns",
      "climate_adaptation": "Heat and disease tolerant",
      "average_weight_male_kg": 600,
      "average_weight_female_kg": 400,
      "temperament": "Docile",
      "lifespan_years": 12
    },
    "Kasargod": {
      "origin": "Kerala, India",
      "purpose": "Low-milk / Household",
      "milk_yield_liters_per_day": "1–3",
      "milk_fat_percentage": "4.0–5.0",
      "physical_traits": "Small, varied coat, short horns",
      "climate_adaptation": "Humid tropics, hardy",
      "average_weight_male_kg": 200,
      "average_weight_female_kg": 150,
      "temperament": "Docile",
      "lifespan_years": 12
    },
    "Kenkatha": {
      "origin": "UP–MP (Ken River), India",
      "purpose": "Draught",
      "milk_yield_liters_per_day": "1–3",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Grey/brown, small to medium horns",
      "climate_adaptation": "Dry heat tolerant",
      "average_weight_male_kg": 380,
      "average_weight_female_kg": 280,
      "temperament": "Hardy",
      "lifespan_years": 12
    },
    "Kherigarh": {
      "origin": "Lakhimpur Kheri, UP, India",
      "purpose": "Draught / Low-milk",
      "milk_yield_liters_per_day": "2–4",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "White/grey, fine head, medium horns",
      "climate_adaptation": "Hot, humid tolerance",
      "average_weight_male_kg": 420,
      "average_weight_female_kg": 310,
      "temperament": "Quiet",
      "lifespan_years": 12
    },
    "Khillari": {
      "origin": "Maharashtra, India",
      "purpose": "Draught",
      "milk_yield_liters_per_day": "2–5",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Grey/fawn, cylindrical horns, tight skin",
      "climate_adaptation": "Hot, dry; excellent endurance",
      "average_weight_male_kg": 450,
      "average_weight_female_kg": 320,
      "temperament": "Active",
      "lifespan_years": 12
    },
    "Krishna_Valley": {
      "origin": "Karnataka, India",
      "purpose": "Draught",
      "milk_yield_liters_per_day": "2–6",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Grey coat, deep body, strong legs",
      "climate_adaptation": "Semi-arid; hardy",
      "average_weight_male_kg": 500,
      "average_weight_female_kg": 350,
      "temperament": "Steady",
      "lifespan_years": 12
    },
    "Malnad_gidda": {
      "origin": "Karnataka (Western Ghats), India",
      "purpose": "Low-milk / Household",
      "milk_yield_liters_per_day": "1–3",
      "milk_fat_percentage": "4.5–5.5",
      "physical_traits": "Very small frame, dark coat",
      "climate_adaptation": "High rainfall forests; parasite tolerant",
      "average_weight_male_kg": 180,
      "average_weight_female_kg": 150,
      "temperament": "Docile",
      "lifespan_years": 12
    },
    "Mehsana": {
      "origin": "Gujarat, India (buffalo)",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "6–12",
      "milk_fat_percentage": "6.5–8.0",
      "physical_traits": "Black to brown, moderately long horns",
      "climate_adaptation": "Heat tolerant",
      "average_weight_male_kg": 600,
      "average_weight_female_kg": 500,
      "temperament": "Calm",
      "lifespan_years": 15
    },
    "Murrah": {
      "origin": "Haryana–Punjab, India (buffalo)",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "8–16",
      "milk_fat_percentage": "6.5–8.2",
      "physical_traits": "Jet black, tightly curled horns",
      "climate_adaptation": "Good in heat with water access",
      "average_weight_male_kg": 650,
      "average_weight_female_kg": 550,
      "temperament": "Docile",
      "lifespan_years": 16
    },
    "Nagori": {
      "origin": "Rajasthan, India",
      "purpose": "Draught",
      "milk_yield_liters_per_day": "2–6",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "White/grey, long limbs, strong withers",
      "climate_adaptation": "Arid heat tolerant",
      "average_weight_male_kg": 500,
      "average_weight_female_kg": 350,
      "temperament": "Active worker",
      "lifespan_years": 12
    },
    "Nagpuri": {
      "origin": "Vidarbha, Maharashtra, India (buffalo)",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "4–7",
      "milk_fat_percentage": "6.5–7.5",
      "physical_traits": "Black with long, flat horns projecting back",
      "climate_adaptation": "Hot, dry tolerance",
      "average_weight_male_kg": 550,
      "average_weight_female_kg": 450,
      "temperament": "Calm",
      "lifespan_years": 15
    },
     "Nili_Ravi": {
      "origin": "Punjab region (India/Pakistan) (buffalo)",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "8–15",
      "milk_fat_percentage": "6.5–8.0",
      "physical_traits": "Black, wall eyes common, broad forehead",
      "climate_adaptation": "Hot climates; thrives with water access",
      "average_weight_male_kg": 650,
      "average_weight_female_kg": 550,
      "temperament": "Docile",
      "lifespan_years": 16
    },
    "Nimari": {
      "origin": "Narmada valley (MP), India",
      "purpose": "Draught / Low-milk",
      "milk_yield_liters_per_day": "2–5",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Red/brown coat, medium horns",
      "climate_adaptation": "Heat and dry tolerance",
      "average_weight_male_kg": 420,
      "average_weight_female_kg": 300,
      "temperament": "Hardy",
      "lifespan_years": 12
    },
    "Ongole": {
      "origin": "Andhra Pradesh, India",
      "purpose": "Draught / Dual",
      "milk_yield_liters_per_day": "2–5",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "White/grey, massive hump, long legs",
      "climate_adaptation": "Hot coastal; disease resistant",
      "average_weight_male_kg": 600,
      "average_weight_female_kg": 400,
      "temperament": "Bold, active",
      "lifespan_years": 12
    },
    "Pulikulam": {
      "origin": "Tamil Nadu, India",
      "purpose": "Draught",
      "milk_yield_liters_per_day": "1–3",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Dark coat, sturdy build, short horns",
      "climate_adaptation": "Dry tracts; disease hardy",
      "average_weight_male_kg": 380,
      "average_weight_female_kg": 280,
      "temperament": "Hardy",
      "lifespan_years": 12
    },
    "Rathi": {
      "origin": "Rajasthan, India",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "6–10",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "Brown to red with white patches; deep body",
      "climate_adaptation": "Arid heat tolerant",
      "average_weight_male_kg": 450,
      "average_weight_female_kg": 325,
      "temperament": "Docile",
      "lifespan_years": 12
    },
    "Red_Dane": {
      "origin": "Denmark",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "18–28",
      "milk_fat_percentage": "4.1–4.4",
      "physical_traits": "Solid red coat, large frame",
      "climate_adaptation": "Temperate",
      "average_weight_male_kg": 900,
      "average_weight_female_kg": 600,
      "temperament": "Calm",
      "lifespan_years": 9
    },
    "Red_Sindhi": {
      "origin": "Sindh (Pakistan/India)",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "8–12",
      "milk_fat_percentage": "4.0–5.0",
      "physical_traits": "Uniform deep red coat; small horns",
      "climate_adaptation": "Hot climate; disease resistant",
      "average_weight_male_kg": 500,
      "average_weight_female_kg": 320,
      "temperament": "Docile",
      "lifespan_years": 12
    },
    "Sahiwal": {
      "origin": "Punjab region (Pakistan/India)",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "8–15",
      "milk_fat_percentage": "4.5–5.5",
      "physical_traits": "Reddish dun coat, loose skin, prominent hump",
      "climate_adaptation": "Outstanding heat tolerance; tick resistance",
      "average_weight_male_kg": 600,
      "average_weight_female_kg": 400,
      "temperament": "Gentle",
      "lifespan_years": 12
    },
    "Surti": {
      "origin": "Gujarat, India (buffalo)",
      "purpose": "Milk",
      "milk_yield_liters_per_day": "5–8",
      "milk_fat_percentage": "7.0–8.0",
      "physical_traits": "Compact, sickle horns, wedge-shaped body",
      "climate_adaptation": "Good in warm, humid climates",
      "average_weight_male_kg": 500,
      "average_weight_female_kg": 400,
      "temperament": "Docile",
      "lifespan_years": 15
    },
    "Tharparkar": {
      "origin": "Thar desert (India/Pakistan)",
      "purpose": "Milk / Draught",
      "milk_yield_liters_per_day": "8–12",
      "milk_fat_percentage": "4.0–4.5",
      "physical_traits": "White to light grey, deep barrel, black points",
      "climate_adaptation": "Excellent desert heat tolerance",
      "average_weight_male_kg": 500,
      "average_weight_female_kg": 350,
      "temperament": "Docile",
      "lifespan_years": 15
    },
     "Toda": {
        "origin": "Nilgiri Hills, Tamil Nadu, India",
        "purpose": "Milk",
        "milk_yield_liters_per_day": "3–5",
        "milk_fat_percentage": "6.0–7.0",
        "physical_traits": "Medium size, long curved horns, white coat with black markings",
        "climate_adaptation": "Well-suited to hilly and cool climates",
        "average_weight_male_kg": 400,
        "average_weight_female_kg": 300,
        "temperament": "Docile",
        "lifespan_years": 15
    },
    "Vechur": {
        "origin": "Kerala, India",
        "purpose": "Milk",
        "milk_yield_liters_per_day": "2–3",
        "milk_fat_percentage": "6.0–7.5",
        "physical_traits": "Smallest cattle breed in the world, dwarf stature, short horns",
        "climate_adaptation": "Excellent adaptability to hot and humid tropical climate",
        "average_weight_male_kg": 150,
        "average_weight_female_kg": 130,
        "temperament": "Gentle",
        "lifespan_years": 12
    },
    "Umblachery": {
        "origin": "Tamil Nadu, India",
        "purpose": "Draught",
        "milk_yield_liters_per_day": "1–2",
        "milk_fat_percentage": "4.5–5.0",
        "physical_traits": "Medium size, grey coat, strong legs, moderate hump",
        "climate_adaptation": "Adapted to hot, humid plains and resistant to local diseases",
        "average_weight_male_kg": 400,
        "average_weight_female_kg": 300,
        "temperament": "Hardy and active",
        "lifespan_years": 14
    }

  }
}
